version: '3'

services:
  top-api:
    container_name: TOP_API
    build: './'
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env

  mongo:
    image: mongo:5.0.5
    container_name: mongo_nestjs
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zephyr
      - MONGO_INITDB_ROOT_PASSWORD=Zephyr_Password
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-5.0:/data/db