name: Publish Docker

on: 
  push:
    branches: [master]

jobs: 
  build:
    runs-on: debian
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/mad-zephyr/nestjs-learn/nestjs-learn
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}